### ISSUE TITLE
ImGui Error

### ISSUE THREAD

**Issue by Tosox** [rdbo/DX9-BaseHook#2]
Hello, this is probably not a problem with a hook, but a problem on ImGui or CSGO, but I can not interact with the menu when I open it. I have already looked on the internet, for example on Unknowncheats and GuidedHacking, if there is a fix for it, but I have not found anything that works for me. Also I updated ImGui and use the latest version now, but it doesn’t seem to help. Do you know a fix for that? Thank you

**Comment by rdbo** [comment]
I just downloaded the project, compiled and injected into the game using ManualMap, as the game will only load signed DLLs or something like that. Works just fine.

**Comment by Tosox** [comment]
Ok thats weird. Everything is fine on my other pc, but on the pc where I am coding it on, it does not work :(
