### ISSUE TITLE
Weird Colors

### ISSUE THREAD

**Issue by ir** [rdbo/DX9-BaseHook#3]
Seems kind of like it loads the menu twice? Colors are wayy more saturated
I am only injecting once. Using 1.2

When resizing the menu it does seem to have another menu below it with normal colors

![image](https://user-images.githubusercontent.com/71415296/116770344-98c11280-a9ef-11eb-8caa-a4ecab13475c.png)

![image](https://user-images.githubusercontent.com/71415296/116770282-00c32900-a9ef-11eb-9d5a-2f130e6a8298.png)

**Comment by rdbo** [comment]
Well, the hooks are working and the window is showing, probably something game specific.

**Comment by ir** [comment]
I forgot to add, when restarting my pc, the colors go back to normal. This issue does not happen with https://github.com/rdbo/ImGui-DirectX-9-Kiero-Hook

Not only does this happen with my own injector, but also others (Xenos, AlisaAlis)

The same issue occurs in CSGO as well:
![image](https://user-images.githubusercontent.com/71415296/116798433-d8ddcf00-aa9b-11eb-8045-e9263344e205.png)
