### ISSUE TITLE
Can't press anything

### ISSUE THREAD

**Issue by Ruqen** [rdbo/DX9-BaseHook#4]
Compiling it (Debug x86) then injecting it, and I can't press anything. It's like an image, I can't move anything, I can't press anything either. Any fixes?

**Comment by rdbo** [comment]
It depends a lot on what game you're using this in. It generally happens when you don't hook the WndProc or hook it unproperly. This project already does that, so I can't see why wouldn't it work.

**Comment by Ruqen** [comment]
I'm trying to inject it in CS:GO, like in other issue when windowed then full screen but doing that every time I inject is just disturbing. Like Osiris doesn't require that, it just works when you are in full screen.

**Comment by rdbo** [comment]
Oh, now that you said it, I had this problem as well. I never figured out why it didn't work directly with fullscreen, and I haven't messed with Windows for a while now.

**Comment by Ruqen** [comment]
> Oh, now that you said it, I had this problem as well. I never figured out why it didn't work directly with fullscreen, and I haven't messed with Windows for a while now.

Here's a CSGO project that supports it!
https://github.com/danielkrupinski/Osiris

I think you can get some ideas from it.

I want to make a new project using your hook so

**Comment by rdbo** [comment]
I took a quick look, and the only difference I see is that they don't seem to be creating a dummy device for DX9, and instead are just finding the functions from memory. Not sure what difference would that make, but maybe it's a start point.

**Comment by Ruqen** [comment]
> I took a quick look, and the only difference I see is that they don't seem to be creating a dummy device for DX9, and instead are just finding the functions from memory. Not sure what difference would that make, but maybe it's a start point.

Yes! I would like to see that becoming a feature in this hook

**Comment by Ruqen** [comment]
Any update?

**Comment by Ruqen** [comment]
BTW, another thing Osiris has, when you press the key to open the mouse pops up automatically, no need to press ESC in CS:GO or other stuff

**Comment by rdbo** [comment]
These things are all game-specific as far as I'm aware, so I can't implement them in a universal DX9 hook. Besides, I'm not on Windows so it's not easy to work from a weak VM.
