### ISSUE TITLE
Nothing happens when calling the DLL using the LoadLibraryA method.

### ISSUE THREAD

**Issue by ghost** [rdbo/DX9-BaseHook#6]
I'm using a DLL Wrapper just to load the DLL created by your project, it works great with D3D11 versions of your projects, both x86/x64 and versions with or without libmem, but here with "DX9-BaseHook" nothing happens. Nota: Injecting the DLL works, but loading via the LoadLibraryA method does not. The DLL is working, and even loading the DLL, there is information in the HANDLE.

By attaching the DX9-BaseHook in DLL Wrapper.

```c++
HANDLE GuiDLL = LoadLibraryA("d3d9gui.dll");
if (GuiDLL == NULL) {
    MessageBoxA(NULL, "The d3d9gui DLL was not found.", "Failed!", MB_OK);
}
```

**Comment by ghost** [comment]
I put a Sleep() in the MainThread function, for some reason this worked. It is possible to implement something smarter that waits the time really necessary.

```c++
DWORD WINAPI MainThread(LPVOID lpThreadParameter)
{
	Sleep(6000);
	Base::Data::hModule = (HMODULE)lpThreadParameter;
	Base::Init();
	return TRUE;
}
```

**Comment by rdbo** [comment]
> I put a Sleep() in the MainThread function, for some reason this worked. It is possible to implement something smarter that waits the time really necessary.
> 
> ```c++
> DWORD WINAPI MainThread(LPVOID lpThreadParameter)
> {
> 	Sleep(6000);
> 	Base::Data::hModule = (HMODULE)lpThreadParameter;
> 	Base::Init();
> 	return TRUE;
> }
> ```

That's weird. Can't say for sure what it is, since I no longer use Windows.

**Comment by ghost** [comment]
Perhaps something related to the speed at which the DLL is injected in this case, "there's no way" to achieve such speed by manually injecting the DLL, Sleep() gives enough time for the game to open correctly before executing.
